<?php
// Apple APNS Variables
define('PUSH_NOTIFICATIONS_APNS_CERTIFICATE', 'apns-dev.pem');
define('PUSH_NOTIFICATIONS_APNS_PASSPHRASE', '123456');

// GCM API KEY Credentials.
define('PUSH_NOTIFICATIONS_GCM_API_KEY', 'AIzaSyDOV18d2SRFt2IXK8SHCKISLdvP6fQsBxM');
// C2DM Credentials.
define('PUSH_NOTIFICATIONS_C2DM_USERNAME', '');
define('PUSH_NOTIFICATIONS_C2DM_PASSWORD', '');

// Baidu API KEY
define('PUSH_NOTIFICATIONS_BAIDU_API_KEY', 'zbtzQyrBjjczyRVKAix0aMuF');
define('PUSH_NOTIFICATIONS_BAIDU_SECRET_KEY', 'eLG48VcQjjYxyTx8ZzYWdBwu4wo1uN1K');

?>